### PR TITLE
Run CI on all branches

### PR DESCRIPTION
**Pull request by cjdenio**
It's a good idea to run CI on every branch, so issues can be caught before a PR is created

### CODE REVIEW

**Comment by cjdenio** [comment]
@vercel go away

**Comment by anirudhb** [comment]
CI is still checked on PRs so I don't see the point in this, especially with draft PRs. Closing since it adds duplicate checks for PRs.

**Comment by cjdenio** [comment]
The point is that you're made aware of integration issues before opening a PR.

**Comment by anirudhb** [comment]
Doesn't particularly make sense-- draft PRs exist for a reason

**Pull request closed without merging**
