### PR TITLE
Add user to team upon creation

### PR DESCRIPTION
**Pull request by cjdenio**
Automatically adds the authenticated user to a team when they create one

### CODE REVIEW

**Review by anirudhb — CHANGES_REQUESTED** [review]
This behavior doesn't make sense at least to me.
1) You don't have to be part of a team in order to view it
2) The API endpoint this targets is `POST /api/teams` which should not be associating a team with a user as it's not specified in the endpoint.
3) If this were to be implemented it makes most sense as `POST /api/users/me/teams` since it explicitly shows that you are adding a team to the *current* user, and not just creating a team in general.

**Comment by cjdenio** [comment]
I don't understand why it should be possible to create a team without any users in it :confused:

If you're creating a team through the UI, you'd expect to be automatically added to it.

**Comment by anirudhb** [comment]
As I mentioned in 3), this can definitely be implemented in a `POST /api/users/me/teams` endpoint. But it doesn't really make sense for `POST /teams` (tbh, the entire endpoint doesn't make sense either. It should be removed now that we have authenticated users)

**Comment by cjdenio** [comment]
I'm not sure I agree; `POST /teams` makes sense in my opinion as the primary action is creating a team. `POST /users/me/teams` sounds more like "add a team to my account", which isn't the primary goal of the endpoint.

**Review by anirudhb — APPROVED** [review]
Fair, lgtm in that case

**Pull request merged**
