### PR TITLE
Update team avatar via API

### PR DESCRIPTION
**Pull request by cjdenio**
This PR adds an `Avatar` field to the `PATCH /teams/:id` endpoint.

### CODE REVIEW

**Review by anirudhb — APPROVED** [review]

**Review by anirudhb — CHANGES_REQUESTED** [review]
Fix the frontend "invite members" since this breaks that

Probably better is to just make all parameters optional

**Comment by cjdenio** [comment]
This shouldn't break anything; the field isn't required.

GORM only updates non-nil-value fields: https://gorm.io/docs/update.html#Updates-multiple-columns

**Comment by anirudhb** [comment]
No it does break things because BindJSON fails

**Comment by cjdenio** [comment]
`BindJson` doesn't fail, it just sets the fields to their nil values (`""` for strings). I've tested it:
Screen Shot 2021-05-01 at 5 35 19 PM

**Review by anirudhb — APPROVED** [review]

**Pull request merged**
