### PR TITLE
fix(frontend): resolve few issues with frontend

### LINKED ISSUE #86: Rename frontend routes
Rename frontend routes so they are consistent with the API structure. Currently teams are at `/team/:id` on the frontend so make it consistent with the API and change it to `/teams/:id`. Repeat for all inconsistent pages.

### PR DESCRIPTION
**Pull request by veritem**
fix #86

### CODE REVIEW

**Review by anirudhb — CHANGES_REQUESTED** [review]
lgtm on #86 (need to update the Swagger definition though). One thing: we don't really want a 500 page (despite the misleading instructions in #75, I'll fix that). We would just want to overhaul the "app not found page" and that's static HTML so it'll be a little bit harder to fix.

**Comment by veritem** [comment]
@anirudhb  fixed swagger definition

**Comment by anirudhb** [comment]
The swagger definition is in `swagger.yaml`, and the other change (fix the app not found page, not the 500 page) hasn't been addressed. Please fix those first and I'll review afterwards.

**Comment by veritem** [comment]
what do you mean by app not found is it `404` page

**Comment by anirudhb** [comment]
The app not found page is [here](https://github.com/hackclub/hack-as-a-service/blob/master/dokku_deploy/var/lib/dokku/data/nginx-vhosts/dokku-errors/haas/404-error.html) if you're looking to restyle that. Otherwise, you can remove it from your PR since the other parts look good.

**Comment by veritem** [comment]
@anirudhb fixed

**Review by anirudhb — APPROVED** [review]
lgtm! thanks for the contribution

**Pull request merged**
