### PR TITLE
Create package-ci.yml

### PR DESCRIPTION
**Pull request by veritem**
Silence dependabot PRs to be auto merged Automatically once ci passes.

### CODE REVIEW

**Review by jasonappah — CHANGES_REQUESTED** [review]
Looks good to me so far, but I'd prefer to use the regular build jobs and add a `needs` key to the `automerge` job so we aren't building the frontend twice unnecessarily.

**Comment by veritem** [comment]
@jasonappah That makes sense fixed

**Review by jasonappah — APPROVED** [review]
Looks good to me

**Comment by anirudhb** [comment]
Pretty sure this can be closed since auto-merge provides similar functionality without needing an extra workflow

**Comment by veritem** [comment]
@anirudhb  auto-merge really can save sometimes though if the package has a breaking change it can't be merged.

**Comment by anirudhb** [comment]
If there is a breaking change we have to handle it manually anyways.

**Comment by veritem** [comment]
Yeah, but path and minor versions get's auto-merged anyways

**Pull request closed without merging**
