### PR TITLE
Fix deploy sync and fetch proper default branch

### PR DESCRIPTION
**Pull request by anirudhb**
Fixes issues where Git repositories didn't sync on deploy.

Also adds libgit2 as a runtime dependency, which is now installed in the Dockerfile.

### CODE REVIEW

**Comment by anirudhb** [comment]
Lint is dying for some reason. Not sure why.

**Review by jasonappah — APPROVED** [review]
Doesn't look like anything will break, so approving

**Review by cjdenio — APPROVED** [review]
lgtm, just delete [this line](https://github.com/hackclub/hack-as-a-service/blob/4fe7896d74da7c3caa75d242ca3e832e49d1d613/pkg/api/builds/logs.go#L9) to fix linting

**Comment by anirudhb** [comment]
rip lint

**Pull request merged**
