### PR TITLE
Remove unsound endpoints

### LINKED ISSUE #77: Remove unsound endpoints
Some endpoints are currently unsound, such as `DELETE /teams/:id` since they allow for orphaned resources to be created which cannot ever be accessed again. Remove or rework these endpoints so that this is not possible.

### PR DESCRIPTION
**Pull request by anirudhb**
Fixes #77

### CODE REVIEW

**Comment by jasonappah** [comment]
I don't have any issues with this but why are we doing this again? I didn't understand the issue description

**Comment by anirudhb** [comment]
Basically rn the API lets me delete a team that contains apps. Then those apps get orphaned (as their corresponding team is now deleted) and it's impossible to ever access them through the API (due to permission checks).

**Review by jasonappah — APPROVED** [review]
Ahh makes sense. So we'll reintroduce this later with a check to see if a team has any associated apps?

**Comment by anirudhb** [comment]
Yep. See #79

**Pull request merged**
