### PR TITLE
Fix Fonts

### PR DESCRIPTION
**Pull request by sampoder**

### CODE REVIEW

**Review by jasonappah — APPROVED** [review]

**Review by cjdenio — APPROVED** [review]

**Review by cjdenio — CHANGES_REQUESTED** [review]
Please run `yarn format:write` quickly

**Comment by l3gacyb3ta** [comment]
If you run ```yarn format:write``` in the frontend dir, it should fix that issue!  
Oh, sorry didn't see Caleb's comment lol.

**Comment by l3gacyb3ta** [comment]
I fixed it!

**Review by cjdenio — APPROVED** [review]
lgtm!

**Pull request merged**
