### PR TITLE
HaaS Landing Page

### PR DESCRIPTION
**Pull request by faisalsayed10**
Tried building the landing page referring the Figma mock-ups.

### CODE REVIEW

**Review by jasonappah — CHANGES_REQUESTED** [review]
Looks good to me minus 2 things:
- Could you make the wave thing larger like it is on the Figma?
- Can you run `yarn run format:write` to format the code properly?

**Review by anirudhb — CHANGES_REQUESTED** [review]
lgtm
Few things:
* Could you keep this page at /landing and also add a route in pkg/frontend/routes.go? We don't currently want this to be the index page until this is complete.
* Run prettier, since frontend format checks are failing. (gofmt for backend)

**Comment by faisalsayed10** [comment]
alright

**Comment by faisalsayed10** [comment]
@jasonappah the wave thingy is at its original size (same as figma). should I still increase its size?

**Comment by faisalsayed10** [comment]
Also ran `yarn run format:write`, also was using prettier as default. I think its still gonna fail in terms of formatting, what do? (lets hope it doesnt)

**Review by anirudhb — APPROVED** [review]
lgtm

**Comment by jasonappah** [comment]
Ah you're right, I wouldn't increase the size of the wave, but could you set the background image to be on the parent Box instead of the h1?

**Comment by faisalsayed10** [comment]
sure

**Review by jasonappah — APPROVED** [review]
Awesome, merging

**Pull request merged**
