### PR TITLE
(WIP) feat: HaaS CLI

### LINKED ISSUE #120: HaaS CLI
A CLI for managing apps, streaming logs, viewing billing, etc. (basically Heroku's CLI but better)

(i wouldn't be opposed to writing this in a non-Go language)

### PR DESCRIPTION
**Pull request by veritem**
fix #120

### CODE REVIEW

**Comment by jasonappah** [comment]
Correct me if I'm wrong, but shouldn't this be outside `pkg` since this is basically separate from the backend? Like in a `cli` folder or something?

**Review by cjdenio — CHANGES_REQUESTED** [review]
This is a great start! Would you mind moving the CLI to a top-level `cli/` directory and initialize a Go module in it (`go mod init github.com/hackclub/hack-as-a-service/cli`)? As this is a separate application from the API, it would be a good idea to keep dependencies separate as well.

**Comment by veritem** [comment]
Thanks

**Comment by gleich** [comment]
Hey @makuzaverite! We are actually going to start the CLI once we reach MVP (aka v1.0.0) as seen in #120. It should also go in a different repo so we don't create a super monorepo here (it is already kinda bad rn imo). I love the enthusiasm though! I would love to have you help out once we get started :)

**Comment by anirudhb** [comment]
This PR seems fine to me. Reopening as it could be a good test fixture pre-launch.

**Comment by veritem** [comment]
Hi, @Matt-Gleich  I started working on this one though I know it will be added in after 1.0.0 that's why I added it to drafts.

**Comment by quackduck** [comment]
@Matt-Gleich as per previous discussions, we had decided to just go with keeping it in one repo, right @jasonappah and @cjdenio

**Pull request closed without merging**
