### PR TITLE
5/2/2021 progress report

### PR DESCRIPTION
**Pull request by anirudhb**
[Rendered](https://github.com/hackclub/hack-as-a-service/blob/progress-report-5-2-2021/progress/5-2-2021.md)

### CODE REVIEW

**Review by faisalsayed10 — APPROVED** [review]

**Review by cjdenio — APPROVED** [review]
lgtm!

**Review by cjdenio — CHANGES_REQUESTED** [review]
Remember to update the `README.md` in the progress reports directory

**Review by jasonappah — APPROVED** [review]
lgtm! damn we got a lot done this week.

**Review by sarthaktexas — APPROVED** [review]

**Review by bellesea — COMMENTED** [review]
looks awesome :))

**Review by cfanoulis — APPROVED** [review]
hey look ma! my name's on there

lgtm~

**Review by cjdenio — APPROVED** [review]
yeet

**Pull request merged**
