### PR TITLE
Update Nginx configuration

### PR DESCRIPTION
**Pull request by cjdenio**
This PR updates the Nginx config to properly serve HTTPS for 404s on https://hackclub.app :tada:

### CODE REVIEW

**Review by sarthaktexas — APPROVED** [review]

**Review by anirudhb — CHANGES_REQUESTED** [review]
lgtm- any reason that we switched to spaces? I would prefer to keep it as tabs

**Comment by cjdenio** [comment]
No particular reason; I'll switch it over

**Review by anirudhb — CHANGES_REQUESTED** [review]
double tabs?

**Comment by cjdenio** [comment]
Oops, apparently `:set noexpandtab` doesn't solve everything 😅

**Review by anirudhb — APPROVED** [review]

**Pull request merged**
