### PR TITLE
Addons page

### PR DESCRIPTION
**Pull request by jasonappah**
This PR creates the addons page and slightly refactors other pages so I don't need to rebuild the same components.

### CODE REVIEW

**Comment by jasonappah** [comment]
Holding on this until Chakra UI migration is complete.

**Comment by anirudhb** [comment]
Chakra UI migration is complete.

**Comment by jasonappah** [comment]
I think this should be good for review, here's a quick screen rec of how it looks:
https://user-images.githubusercontent.com/30608521/117555133-3638c980-b022-11eb-81df-b712bf4d2e20.mov

Obviously we don't have the Addons API ready yet, so should we just hold off on merging this until then, or just not include that page in the menu for now?

**Review by veritem — APPROVED** [review]
LGTM

**Pull request merged**
