### PR TITLE
Initial DB setup

### LINKED ISSUE #9: Setup Postgres / Database
Going to use [GORM](https://gorm.io) for this. Likely going to add a postgres addon to the dokku app and connect to that. We probably want to generate our own user IDs for each user that signs up and store things like their slack UID etc.

It's probably easier to assign each app an owner(s) than to have a list of apps that each user owns. This also works well with SQL since relational tables and stuff. And it makes collaboration/permissions easier in the future.

I'm planning to work on this soon.

### PR DESCRIPTION
**Pull request by anirudhb**
Uses postgres currently.

Closes #9

### CODE REVIEW

**Comment by cjdenio** [comment]
Maybe the database logic shouldn't be in the `dokku` package? I envisioned it as only containing the RPC client.

**Review by cjdenio — CHANGES_REQUESTED** [review]
2 quick things:

- Dokku's Postgres plugin links to apps via a Postgres URL, so could this respect the DATABASE_URL environment variable? (example [here](https://github.com/taskalla/api/blob/7a448fccbeb56139c3e30b33f0e702bbaafdb08b/pkg/db/db.go#L18-L32))
- Some private functions are written in snake_case, while Go convention is to write them in camelCase

Other than that, looks good to me!

**Comment by anirudhb** [comment]
Done.

**Comment by cjdenio** [comment]
The postgres URL will look like `postgres://user:pass@host:port/db`, so you'll need to parse it with `url.Parse()`

**Review by cjdenio — APPROVED** [review]

**Pull request merged**
